server:
  port: 8080

spring:
  application:
    name: dw-test-demo
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo?autoCommit=true&useUnicode=true&autoReconnect=true&characterEncoding=UTF-8&useSSL=false
    #url: jdbc:mysql://123.57.53.82:3306/demo?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: root
    password: root
    timeout: 60000ms
  redis:
    database: 1
    host: 123.57.53.82
    port: 6379
    password: root
    lettuce:
      pool:
        max-active: 300
        max-wait: 10000
        max-idle: 200
        min-idle: 50
    timeout: 20000ms
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 127.0.0.1:9300 # es的连接地址及端口号
      cluster-name: elasticsearch # es集群的名称

  #发送邮件
  mail:
    host: smtp.qq.com
    username: 1074501328@qq.com
    password: rfmrqwdbbadzhbbd
    port: 587
  smtp:
    auth: true
    starttls:
      enable: true
      required:
#添加RabbitMQ的相关配置
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    username: admin
    password: admin
    publisher-confirms: true #消息发送到交换器确认
    publisher-returns: true #消息发送到队列确认

#mybatis
mybatis:
  type-aliases-package: com.dw.cloud.Entity
  mapper-locations: classpath*:mapper/*.xml

#配置分页插件pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com:
      dw:
        demo:
          mapper: DEBUG
#
mail:
  from: 1074501328@qq.com
  fromName: admin


